nucleos_lastfm_success:
    path:   /auth/success
    defaults:  { _controller: 'Nucleos\LastFmBundle\Action\AuthSuccessAction' }

nucleos_lastfm_error:
    path:   /auth/error
    defaults:  { _controller: 'Nucleos\LastFmBundle\Action\AuthErrorAction' }

nucleos_lastfm_check:
    path:   /auth/_check
    defaults:  { _controller: 'Nucleos\LastFmBundle\Action\CheckAuthAction' }

nucleos_lastfm_auth:
    path:   /auth
    defaults:  { _controller: 'Nucleos\LastFmBundle\Action\StartAuthAction' }
