core23_lastfm_success:
    path:   /auth/success
    defaults:  { _controller: 'Core23\LastFmBundle\Action\AuthSuccessAction' }

core23_lastfm_error:
    path:   /auth/error
    defaults:  { _controller: 'Core23\LastFmBundle\Action\AuthErrorAction' }

core23_lastfm_check:
    path:   /auth/_check
    defaults:  { _controller: 'Core23\LastFmBundle\Action\CheckAuthAction' }

core23_lastfm_auth:
    path:   /auth
    defaults:  { _controller: 'Core23\LastFmBundle\Action\StartAuthAction' }
